### ISSUE TITLE
Graduate to main conda organization

### ISSUE THREAD

**Issue by dholth** [conda/conda-package-streaming#31]
I would like to make this project a dependency of `conda-package-handling` -> `conda`, and move it out of the conda incubator to the main conda organization.

**This would give us 2x faster `.conda` handling and would allow us to stop relying on a custom `libarchive` fork.**

This is also related to another graduation application: https://github.com/conda-incubator/conda-index/issues/59

**Comment by jezdez** [comment]
@conda-incubator/steering 

This proposal falls under the **[Incorporate a Software Project into the main conda Organization](https://github.com/conda-incubator/governance/tree/eaf59a5779dc1f678bee4453ceb92fd733e7306a#incorporate-a-software-project-into-the-main-conda-organization)** policy of the [conda governance policy](https://github.com/conda-incubator/governance), please vote and/or comment on this proposal.

It **needs 60% of the Steering Council** to vote `yes` to pass.

To vote, please leave `yes`, `no` or `abstain` as comments below this issue.

If you have questions concerning the proposal, please leave a comment below as well.

**This vote will end on 2022-10-07.**

**Comment by beckermr** [comment]
yes

**Comment by jezdez** [comment]
yes

**Comment by marcelotrevisani** [comment]
Yes

**Comment by jaimergp** [comment]
Yes.

**Comment by ocefpaf** [comment]
Yes

**Comment by ericdill** [comment]
yes

**Comment by xhochy** [comment]
yes

**Comment by msarahan** [comment]
yes

**Comment by mariusvniekerk** [comment]
yes

**Comment by goanpeca** [comment]
yes

**Comment by goanpeca** [comment]
yes
