### ISSUE TITLE
`tarfile` filters `DeprecationWarning`

### ISSUE THREAD

**Issue by jaimergp** [conda/conda-package-streaming#87]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

conda-build's CI is plagued with warnings like this:

```
DeprecationWarning: Python 3.14 will, by default, filter extracted tar archives and reject files or modify their metadata. Use the filter argument to control this behavior.
```

conda-package-streaming should start adding the filter option explicitly for Python 3.12+.

### Conda Info

```shell
N/A
```

### Conda Config

```shell
N/A
```

### Conda list

```shell
N/A
```

### Additional Context

See https://github.com/conda/conda-build/pull/5281

**Comment by dholth** [comment]
IIUC we are doing [this weird thing](https://github.com/conda/conda-package-streaming/blob/main/conda_package_streaming/extract.py#L39) instead of filter. Besides having two implementations this should be a helpful change.

**Comment by dholth** [comment]
It looks like we could use the most restrictive data_filter
